version: 1.0.{build}
environment:
  google_signin_secret:
    secure: BLhTA2k65P4a4agqkd5mI3JN+uRypuVFrJoupCZVxhw=
  google_client_id: 1056158958261-u9o1s4i9srb3tr6ksqk1jk3o17h358pc.apps.googleusercontent.com
build_script:
- cmd: >-
    cd client

    npm install

    npm run build
test_script:
- cmd: npm run test:unit
artifacts:
- path: client/dist
deploy:
- provider: S3
  access_key_id: AKIAZ7JVTEWBXKVTBK6C
  secret_access_key:
    secure: 9K0V8jf0ClfPYhOt7r5+G1ItOBftKMAIDk4w+IhthLYseaBDHoIv/cIXXLr100CR
  region: us-west-2
  bucket: colinmxs.com.github.w-rsvp
  unzip: true
  set_public: false